// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.happyhour.json;

import com.happyhour.json.JsonResponsePromotionInstance;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JsonResponsePromotionInstance_Roo_Configurable {
    
    declare @type: JsonResponsePromotionInstance: @Configurable;
    
}
