// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.happyhour.service;


privileged aspect PromotionRequestProcessedServiceImpl_Roo_Service {
    
    
}
