// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.happyhour.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuarioServiceImpl_Roo_Service {
    
    declare @type: UsuarioServiceImpl: @Service;
    
    declare @type: UsuarioServiceImpl: @Transactional;
    
    
}
