// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.happyhour.entity;

import com.happyhour.entity.Authority;

privileged aspect Authority_Roo_JavaBean {
    
    public String Authority.getRoleName() {
        return this.roleName;
    }
    
    public void Authority.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
