// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.happyhour.controller;

import com.happyhour.controller.UsuarioController;
import com.happyhour.service.UsuarioService;
import org.springframework.beans.factory.annotation.Autowired;

privileged aspect UsuarioController_Roo_Controller {
    
    @Autowired
    UsuarioService UsuarioController.usuarioService;
    
}
